#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
npm run format 
npm test
# git add -A .

# Check branch naming
current_branch=$(git symbolic-ref --short HEAD)
branch_pattern="^(feature|bugfix|hotfix)\/[a-zA-Z0-9_-]+$"

if ! [[ "$current_branch" =~ $branch_pattern ]]; then
  echo "Error: Invalid branch name. Branch names must match the pattern: $branch_pattern"
  exit 1
fi





git add -A .
